.TH UDISKS\-GLUE 1 2011-04-20 "udisks\-glue" "udisks\-glue Manual"
.SH NAME
udisks\-glue \- A tool to associate udisks events to user\-defined actions
.SH SYNOPSIS
.B udisks\-glue
[\fB\-c \fIconfig\-file\fR]
[\fB\-f\fR]
[\fB\-p \fIpidfile\fR]
[\fB\-s\fR]
.br
.B udisks\-glue
[\fB\-h\fR]
.SH DESCRIPTION
udisks\-glue listens for UDisks DBus events and reacts to them according to the configuration. It can be used to automatically mount removable devices or perform arbitrary actions in response to events related to removable devices.
.SH OPTIONS
.TP 26
.B \-c\fR/\fB\-\-config \fIconfig\-file
Use \fIconfig\-file\fR as the configuration file
.TP
.B \-f\fR/\fB\-\-foreground
Remain in foreground (don't daemonize)
.TP
.B \-h\fR/\fB\-\-help
Display usage information and exit
.TP
.B \-p\fR/\fB\-\-pidfile \fIpidfile
Use \fIpidfile\fR file as the pidfile
.TP
.B \-s\fR/\fB\-\-session
Enable ConsoleKit session support
.SH FILES
A configuration file must exist or udisks\-glue will fail to start up. If no configuration file is specified by command line arguments, udisks\-glue will look for the following configuration files (in this order):
.TP 3
.B 1.
.I $HOME\fB/.udisks\-glue.conf
.TP
.B 2.
.I $XDG_CONFIG_HOME\fB/udisks\-glue/config
.TP
.B 3.
.B /etc/udisks\-glue.conf
.TP
.B 4.
.I $DIR\fB/udisks\-glue/config\fR for each dir in \fI$XDG_CONFIG_DIRS
.SH SEE ALSO
.B udisks\fR(1),
.B udisks\-glue.conf\fR(5)
.B udisks\fR(7),
.B udisks\-daemon\fR(8)
